### ISSUE TITLE
NoClassDefFoundError: scala/Product

### ISSUE THREAD

**Issue by rsimon** [dasmiq/passim#11]
Hi,

I'm trying to get a basic example running and, so far, have managed to get Passim to build correctly, I think. However when I run using  `passim input.jsonl output` I get an error in the main `PassimApp` file about a missing core Scala class. (I'm attaching the dump for completeness below.) This looks like some kind of Scala 2.11/2.12 mismatch I think. I tried re-compiling with Scala 2.12.10, but same results.

Any hints on what I might be doing wrong or where my configuration problem lies?

```sh
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
        at scopt.OptionParser.<init>(options.scala:181)
        at passim.PassimApp$$anon$1.<init>(PassimApp.scala:1066)
        at passim.PassimApp$.main(PassimApp.scala:1066)
        at passim.PassimApp.main(PassimApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 16 more
```

**Comment by rsimon** [comment]
Another thought: could this be related to mismatch between Passim and the installed Spark version? (Im using Spark 3.0.1 Hadoop 2.7.)

**Comment by rsimon** [comment]
P.S.: figured out the problem. It was an incompatible Spark version. For posterity: I could only make it work in Scala 2.11 & had to make sure the Spark version was also built in Scala 2.11. (In my case the latest version for this was 2.4.7.)
