### ISSUE TITLE
Launching PASSIM

### ISSUE THREAD

**Issue by ir-laboratory** [dasmiq/passim#7]
Hello, I have a problem...

I have installed Apace Spark, JDK 8, Scala, SBT, and I have compiled the Passim project (on WINDOWS)

Now I have in the folder: 

C:\<users>\passim-master\target\scala-2.11

the file: passim_2.11-0.2.0.jar

So I think I should have compiled correctly Passim.

I have also added the folder: 

C:\<users>\passim-master\bin

to my PATH.

Now, when I try, from the command line, to execute:

C:\<users>\passim-master\bin>passim input.json output

I obtain the following error "passim" is not recognized as an internal or external command".

What am I forgetting? I'm no expert in the use of these technologies and I probably lost something on the way...

**Comment by faustusdotbe** [comment]
Hi,

Could you paste your error stack trace?

I too have built a jar on Windows. When I run `spark-submit --class passim.PassimApp  --packages 'com.github.scopt:scopt_2.11:3.5.0,graphframes:graphframes:0.7.0-spark2.4-s_2.11' target\scala-2.11\passim_2.11-0.2.0.jar` from the command line (i.e., the content of `bin\passim`), I have a dependency error (stacktrace below). It looks like it's looking at my `C:\Users\Simon\.ivy2` directory for the dependencies. The jar and the whole project are on `G:\passim`.

System info:
- Windows 10 64 bits
- sbt 0.13.8
- "The current project is built against Scala 2.11.8"
- JDK 8
- "sbt, sbt plugins, and build definitions are using Scala 2.10.7"
- Spark and Hadoop version match the ones in the repo

Thanks!


```
Ivy Default Cache set to: C:\Users\Simon\.ivy2\cache
The jars for the packages stored in: C:\Users\Simon\.ivy2\jars
:: loading settings :: url = jar:file:/G:/passim-master/spark-2.4.3-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
'com.github.scopt#scopt_2.11 added as a dependency
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-3c30d420-8aa8-44d6-befd-5c4d95e7dcc8;1.0
        confs: [default]
:: resolution report :: resolve 983ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   2   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: 'com.github.scopt#scopt_2.11;3.5.0

        ==== local-m2-cache: tried

          file:/C:/Users/Simon/.m2/repository/'com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.pom

          -- artifact 'com.github.scopt#scopt_2.11;3.5.0!scopt_2.11.jar:

          file:/C:/Users/Simon/.m2/repository/'com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.jar

        ==== local-ivy-cache: tried

          C:\Users\Simon\.ivy2\local\'com.github.scopt\scopt_2.11\3.5.0\ivys\ivy.xml

          -- artifact 'com.github.scopt#scopt_2.11;3.5.0!scopt_2.11.jar:

          C:\Users\Simon\.ivy2\local\'com.github.scopt\scopt_2.11\3.5.0\jars\scopt_2.11.jar

        ==== central: tried

          https://repo1.maven.org/maven2/'com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.pom

          -- artifact 'com.github.scopt#scopt_2.11;3.5.0!scopt_2.11.jar:

          https://repo1.maven.org/maven2/'com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.jar

        ==== spark-packages: tried

          https://dl.bintray.com/spark-packages/maven/'com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.pom

          -- artifact 'com.github.scopt#scopt_2.11;3.5.0!scopt_2.11.jar:

          https://dl.bintray.com/spark-packages/maven/'com/github/scopt/scopt_2.11/3.5.0/scopt_2.11-3.5.0.jar

                module not found: graphframes#graphframes;0.7.0-spark2.4-s_2.11'

        ==== local-m2-cache: tried

          file:/C:/Users/Simon/.m2/repository/graphframes/graphframes/0.7.0-spark2.4-s_2.11'/graphframes-0.7.0-spark2.4-s_2.11'.pom

          -- artifact graphframes#graphframes;0.7.0-spark2.4-s_2.11'!graphframes.jar:

          file:/C:/Users/Simon/.m2/repository/graphframes/graphframes/0.7.0-spark2.4-s_2.11'/graphframes-0.7.0-spark2.4-s_2.11'.jar

        ==== local-ivy-cache: tried

          C:\Users\Simon\.ivy2\local\graphframes\graphframes\0.7.0-spark2.4-s_2.11'\ivys\ivy.xml

          -- artifact graphframes#graphframes;0.7.0-spark2.4-s_2.11'!graphframes.jar:

          C:\Users\Simon\.ivy2\local\graphframes\graphframes\0.7.0-spark2.4-s_2.11'\jars\graphframes.jar

        ==== central: tried

          https://repo1.maven.org/maven2/graphframes/graphframes/0.7.0-spark2.4-s_2.11'/graphframes-0.7.0-spark2.4-s_2.11'.pom

          -- artifact graphframes#graphframes;0.7.0-spark2.4-s_2.11'!graphframes.jar:

          https://repo1.maven.org/maven2/graphframes/graphframes/0.7.0-spark2.4-s_2.11'/graphframes-0.7.0-spark2.4-s_2.11'.jar

        ==== spark-packages: tried

          https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.7.0-spark2.4-s_2.11'/graphframes-0.7.0-spark2.4-s_2.11'.pom

          -- artifact graphframes#graphframes;0.7.0-spark2.4-s_2.11'!graphframes.jar:

          https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.7.0-spark2.4-s_2.11'/graphframes-0.7.0-spark2.4-s_2.11'.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: 'com.github.scopt#scopt_2.11;3.5.0: not found

                :: graphframes#graphframes;0.7.0-spark2.4-s_2.11': not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: 'com.github.scopt#scopt_2.11;3.5.0: not found, unresolved dependency: graphframes#graphframes;0.7.0-spark2.4-s_2.11': not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1306)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:315)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```
